# Generated by Django 5.2.4 on 2025-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzduotys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
